#! /bin/sh
export CONDA_FORGE_DOCKER_RUN_ARGS="-v $PWD/environment:/etc/environment --env http_proxy=http://172.17.0.1:3128 --env https_proxy=http://172.17.0.1:3128"
export CI=1
nohup ./build-locally.py linux_ > build.log 2>&1 &
